pipeline:
  lineNodes:
    - name: detect
      order: 1
      valves:
        - name: detectEx
          valveClass: longinus.DetectExValve
          instanceTopic: Longinus.detectEx
        - name: detectRetina
          valveClass: longinus.DetectRetinaValve
          instanceTopic: Longinus.detectRetina
    - name: align
      order: 2
      valves:
        - name: alignFace
          valveClass: longinus.AlignFaceValve
          instanceTopic: Longinus.alignFace
    - name: forward
      order: 3
      valves:
        - name: gaiusForward
          valveClass: gaius.ForwardValve
          instanceTopic: Gaius.Forward
        - name: cassiusForward
          valveClass: cassius.ForwardValve
          instanceTopic: Cassius.Forward
  signleNodes:
    - name: add
      valveClass: irisviel.PersonDBAddRecordValve
      instanceTopic: Irisviel.add_record
    - name: new
      valveClass: irisviel.PersonDBNewValve
      instanceTopic: Irisviel.new
    - name: update
      valveClass: irisviel.PersonDBUpdateRecordValve
      instanceTopic: Irisviel.update_record
    - name: search
      valveClass: irisviel.PersonDBSearchValve
      instanceTopic: Irisviel.search
    - name: delete
      valveClass: irisviel.PersonDBDeleteValve
      instanceTopic: Irisviel.delete
    - name: adds
      valveClass: irisviel.PersonDBAddRecordsValve
      instanceTopic: Irisviel.add_records
    - name: updates
      valveClass: irisviel.PersonDBUpdateRecordsValve
      instanceTopic: Irisviel.update_records
    - name: remove
      valveClass: irisviel.PersonDBRemoveValve
      instanceTopic: Irisviel.remove_record
    - name: removes
      valveClass: irisviel.PersonDBRemoveRecordsValve
      instanceTopic: Irisviel.remove_records
    - name: load
      valveClass: irisviel.PersonDBLoadValve
      instanceTopic: Irisviel.load_databases