pipeline:
  lineNodes:
    - name: detect
      order: 1
      valves:
        - name: detectEx
          valveClass: longinus.DetectExValve
          instanceTopic: Longinus.detectEx
        - name: detectRetina
          valveClass: longinus.DetectRetinaValue
          instanceTopic: Longinus.detectRetina
    - name: align
      order: 2
      valves:
        - name: alignFace
          valveClass: longinus.AlignFaceValue
          instanceTopic: Longinus.alignFace